---
title: "Soc-Info Prior Data Processing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source(here::here("R/soc_info_helpers.R"))
d_path <- "data/01_raw_data/actions_prior/production-results/"
```

## Load raw json data

Use purrr to map our read json function over all files in the raw data directory

```{r}
files <- dir(here(d_path))
df_list <- files %>% purrr::map(~ safe_json_to_df_prior(data_path = d_path, .)) 
```

Look at output to see where errors occurred and then convert to data frame only keeping successful function calls.

```{r}
results <- df_list %>% transpose() 
ok <- results$error %>% map_lgl(is_null)
df <- results$result %>% keep(ok) %>%  map_df(bind_rows) 
```

## Data checks

How many participants in each condition?

```{r}
df %>% 
  distinct(workerid, condition) %>% 
  count(condition) %>% 
  knitr::kable()
```

Convert all strings to lower case.

```{r}
df %<>% mutate_if(is.character, str_to_lower)
```

## Anonymize Turker ids. 

```{r}
df_anonymized <- df %>% 
  select(workerid) %>% 
  distinct() %>% 
  mutate(id = 1:nrow(.)) 

df_wide <- left_join(df, df_anonymized, by = "workerid") %>% 
  select(id, everything(), -workerid)
```

## Write to disk. 

```{r}
write_csv(df_wide, path = here("/data/02_tidy_data", "goal_actions_prior_tidy.csv"))
```
